# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_input = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_input.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_input.setObjectName("tab_input")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 150, 260))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.list_br = QtWidgets.QListView(self.groupBox)
        self.list_br.setGeometry(QtCore.QRect(20, 30, 110, 220))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.list_br.setFont(font)
        self.list_br.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_br.setObjectName("list_br")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 220, 151, 261))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 30, 150, 260))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.list_phone = QtWidgets.QListView(self.groupBox_3)
        self.list_phone.setGeometry(QtCore.QRect(20, 30, 110, 220))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.list_phone.setFont(font)
        self.list_phone.setObjectName("list_phone")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 30, 150, 260))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStatusTip("")
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.list_guzhang = QtWidgets.QListWidget(self.groupBox_4)
        self.list_guzhang.setGeometry(QtCore.QRect(20, 30, 110, 195))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.list_guzhang.setFont(font)
        self.list_guzhang.setObjectName("list_guzhang")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox_4)
        self.btnAdd.setGeometry(QtCore.QRect(20, 230, 110, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(500, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(500, 130, 201, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(501, 221, 32, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_cost = QtWidgets.QLineEdit(self.tab)
        self.txt_cost.setGeometry(QtCore.QRect(550, 221, 131, 19))
        self.txt_cost.setObjectName("txt_cost")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(500, 263, 32, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Cal = QtWidgets.QCalendarWidget(self.tab)
        self.Cal.setEnabled(True)
        self.Cal.setGeometry(QtCore.QRect(460, 260, 248, 183))
        self.Cal.setObjectName("Cal")
        self.txt_date = QtWidgets.QLineEdit(self.tab)
        self.txt_date.setGeometry(QtCore.QRect(550, 260, 110, 25))
        self.txt_date.setObjectName("txt_date")
        self.btnDate = QtWidgets.QPushButton(self.tab)
        self.btnDate.setGeometry(QtCore.QRect(660, 260, 25, 25))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        self.btnDate.setFont(font)
        self.btnDate.setObjectName("btnDate")
        self.txtGz = QtWidgets.QTextEdit(self.tab)
        self.txtGz.setGeometry(QtCore.QRect(500, 50, 201, 51))
        self.txtGz.setObjectName("txtGz")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(500, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_danhao = QtWidgets.QLabel(self.tab)
        self.lbl_danhao.setGeometry(QtCore.QRect(760, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.lbl_danhao.setFont(font)
        self.lbl_danhao.setText("")
        self.lbl_danhao.setObjectName("lbl_danhao")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 360, 71, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_gkName = QtWidgets.QLineEdit(self.tab)
        self.txt_gkName.setGeometry(QtCore.QRect(140, 360, 71, 20))
        self.txt_gkName.setObjectName("txt_gkName")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 400, 71, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txt_gkphone = QtWidgets.QLineEdit(self.tab)
        self.txt_gkphone.setGeometry(QtCore.QRect(140, 400, 171, 20))
        self.txt_gkphone.setObjectName("txt_gkphone")
        self.btn_print = QtWidgets.QPushButton(self.tab)
        self.btn_print.setGeometry(QtCore.QRect(410, 360, 75, 51))
        self.btn_print.setObjectName("btn_print")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(210, 350, 151, 31))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.rd_gkSex1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.rd_gkSex1.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.rd_gkSex1.setFont(font)
        self.rd_gkSex1.setObjectName("rd_gkSex1")
        self.rd_gkSex0 = QtWidgets.QRadioButton(self.groupBox_5)
        self.rd_gkSex0.setGeometry(QtCore.QRect(80, 10, 89, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.rd_gkSex0.setFont(font)
        self.rd_gkSex0.setObjectName("rd_gkSex0")
        self.tab_input.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_input.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tab_input, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.me_br = QtWidgets.QAction(MainWindow)
        self.me_br.setObjectName("me_br")
        self.me_ph = QtWidgets.QAction(MainWindow)
        self.me_ph.setObjectName("me_ph")
        self.me_hit = QtWidgets.QAction(MainWindow)
        self.me_hit.setObjectName("me_hit")
        self.menu.addAction(self.me_br)
        self.menu.addAction(self.me_ph)
        self.menu.addAction(self.me_hit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_input.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "品牌"))
        self.groupBox_2.setTitle(_translate("MainWindow", "品牌"))
        self.groupBox_3.setTitle(_translate("MainWindow", "机型"))
        self.groupBox_4.setTitle(_translate("MainWindow", "故障选择"))
        self.btnAdd.setText(_translate("MainWindow", "生成"))
        self.label.setText(_translate("MainWindow", "维修项目"))
        self.label_2.setText(_translate("MainWindow", "收费"))
        self.label_3.setText(_translate("MainWindow", "日期"))
        self.btnDate.setText(_translate("MainWindow", "E"))
        self.label_4.setText(_translate("MainWindow", "故障现象"))
        self.label_5.setText(_translate("MainWindow", "顾客姓名"))
        self.label_6.setText(_translate("MainWindow", "顾客电话"))
        self.btn_print.setText(_translate("MainWindow", "打印"))
        self.rd_gkSex1.setText(_translate("MainWindow", "先生"))
        self.rd_gkSex0.setText(_translate("MainWindow", "女士"))
        self.tab_input.setTabText(self.tab_input.indexOf(self.tab), _translate("MainWindow", "维修单录入"))
        self.tab_input.setTabText(self.tab_input.indexOf(self.tab_2), _translate("MainWindow", "维修单查询"))
        self.menu.setTitle(_translate("MainWindow", "基本信息"))
        self.me_br.setText(_translate("MainWindow", "品牌维护"))
        self.me_ph.setText(_translate("MainWindow", "机型维护"))
        self.me_hit.setText(_translate("MainWindow", "故障现象维护"))

